baseURL = 'https://effml-postech.github.io/'
languageCode = 'en-us'
title = 'Efficient ML Systems'
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true


[menu]

[params]
  BookSection = 'docs'
  BookRepo = 'https://github.com/effml-postech/effml-postech.github.io'
  BookEditPath = 'edit/main/'
