baseURL = ''
languageCode = 'en-us'
title = 'Efficient ML Systems'
theme = 'hugo-book'

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[menu]


[params]
  BookSection = 'docs'
  BookRepo = 'https://github.com/effml-postech/effml-postech.github.io'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main/'
